/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.notificationcentersdk;

public class AircraftLocationCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AircraftLocationCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AircraftLocationCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AircraftLocationCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_AircraftLocationCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    notificationcenterJNI.AircraftLocationCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    notificationcenterJNI.AircraftLocationCallback_change_ownership(this, swigCPtr, true);
  }

  public void onMessage(AircraftLocation msg) {
    notificationcenterJNI.AircraftLocationCallback_onMessage(swigCPtr, this, AircraftLocation.getCPtr(msg), msg);
  }

  public AircraftLocationCallback() {
    this(notificationcenterJNI.new_AircraftLocationCallback(), true);
    notificationcenterJNI.AircraftLocationCallback_director_connect(this, swigCPtr, true, true);
  }

}
