/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.notificationcentersdk;

public class BusinessManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BusinessManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BusinessManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_BusinessManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BusinessManager(SWIGTYPE_p_std__weak_ptrT_TopicManager_t topic_mgr) {
    this(notificationcenterJNI.new_BusinessManager(SWIGTYPE_p_std__weak_ptrT_TopicManager_t.getCPtr(topic_mgr)), true);
  }

  public void Send(String msg) {
    notificationcenterJNI.BusinessManager_Send(swigCPtr, this, msg);
  }

  public void Observe(SWIGTYPE_p_std__functionT_void_fstd__string_const_RF_t callback) {
    notificationcenterJNI.BusinessManager_Observe(swigCPtr, this, SWIGTYPE_p_std__functionT_void_fstd__string_const_RF_t.getCPtr(callback));
  }

  public void CancelObserve(SWIGTYPE_p_int64_t listen_id) {
    notificationcenterJNI.BusinessManager_CancelObserve(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(listen_id));
  }

  public SWIGTYPE_p_ListenId ListenAircraftLocation(SWIGTYPE_p_OnSubscribeMessageCallback on_messages_callback, SWIGTYPE_p_OnSubscribeResultCallback on_result_callback, String device_sn, SWIGTYPE_p_NotifactionFrequency freq) {
    return new SWIGTYPE_p_ListenId(notificationcenterJNI.BusinessManager_ListenAircraftLocation(swigCPtr, this, SWIGTYPE_p_OnSubscribeMessageCallback.getCPtr(on_messages_callback), SWIGTYPE_p_OnSubscribeResultCallback.getCPtr(on_result_callback), device_sn, SWIGTYPE_p_NotifactionFrequency.getCPtr(freq)), true);
  }

}
