/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_notificationcenter_WRAP_H_
#define SWIG_notificationcenter_WRAP_H_

class SwigDirector_JavaAircraftLocationMsgCallback : public JavaAircraftLocationMsgCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JavaAircraftLocationMsgCallback(JNIEnv *jenv);
    virtual ~SwigDirector_JavaAircraftLocationMsgCallback();
    virtual void onMessage(JavaAircraftLocationMsg const &msg);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_ResultCallback : public ResultCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ResultCallback(JNIEnv *jenv);
    virtual ~SwigDirector_ResultCallback();
    virtual void onResult(long result);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_ConnectionListener : public WebsocketEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ConnectionListener(JNIEnv *jenv);
    virtual ~SwigDirector_ConnectionListener();
    virtual void OnMessage(std::string const &message);
    virtual void OnOpen();
    virtual void OnClose();
    virtual void OnError(std::string const &error);
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<4> swig_override;
};


#endif
