/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.notificationcentersdk;

public final class NotificationCenterErrorCode {
  public final static NotificationCenterErrorCode NotificationCenterErrorCode_NoError = new NotificationCenterErrorCode("NotificationCenterErrorCode_NoError", 0);
  public final static NotificationCenterErrorCode NotificationCenterErrorCode_InvalidParameter = new NotificationCenterErrorCode("NotificationCenterErrorCode_InvalidParameter", -1);
  public final static NotificationCenterErrorCode NotificationCenterErrorCode_NotConnected = new NotificationCenterErrorCode("NotificationCenterErrorCode_NotConnected", -2);
  public final static NotificationCenterErrorCode NotificationCenterErrorCode_SendError = new NotificationCenterErrorCode("NotificationCenterErrorCode_SendError", -3);
  public final static NotificationCenterErrorCode NotificationCenterErrorCode_SubscribeError = new NotificationCenterErrorCode("NotificationCenterErrorCode_SubscribeError", -4);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NotificationCenterErrorCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NotificationCenterErrorCode.class + " with value " + swigValue);
  }

  private NotificationCenterErrorCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NotificationCenterErrorCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NotificationCenterErrorCode(String swigName, NotificationCenterErrorCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NotificationCenterErrorCode[] swigValues = { NotificationCenterErrorCode_NoError, NotificationCenterErrorCode_InvalidParameter, NotificationCenterErrorCode_NotConnected, NotificationCenterErrorCode_SendError, NotificationCenterErrorCode_SubscribeError };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

