/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.notificationcentersdk;

public class SdkInitializeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SdkInitializeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SdkInitializeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SdkInitializeInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_SdkInitializeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLog_path(String value) {
    notificationcenterJNI.SdkInitializeInfo_log_path_set(swigCPtr, this, value);
  }

  public String getLog_path() {
    return notificationcenterJNI.SdkInitializeInfo_log_path_get(swigCPtr, this);
  }

  public void setLog_level(SdkLogLevel value) {
    notificationcenterJNI.SdkInitializeInfo_log_level_set(swigCPtr, this, value.swigValue());
  }

  public SdkLogLevel getLog_level() {
    return SdkLogLevel.swigToEnum(notificationcenterJNI.SdkInitializeInfo_log_level_get(swigCPtr, this));
  }

  public SdkInitializeInfo(String log_path, SdkLogLevel log_level) {
    this(notificationcenterJNI.new_SdkInitializeInfo__SWIG_0(log_path, log_level.swigValue()), true);
  }

  public SdkInitializeInfo(String log_path) {
    this(notificationcenterJNI.new_SdkInitializeInfo__SWIG_1(log_path), true);
  }

  public SdkInitializeInfo() {
    this(notificationcenterJNI.new_SdkInitializeInfo__SWIG_2(), true);
  }

}
