/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.notificationcentersdk;

public class SDKManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected SDKManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDKManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_SDKManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SDKManager() {
    this(notificationcenterJNI.new_SDKManager(), true);
  }

  public void init(SdkInitializeInfo info) {
    notificationcenterJNI.SDKManager_init(swigCPtr, this, SdkInitializeInfo.getCPtr(info), info);
  }

  public boolean isInit() {
    return notificationcenterJNI.SDKManager_isInit(swigCPtr, this);
  }

  public void setWebsocketEventListener(ConnectionListener listener) {
    notificationcenterJNI.SDKManager_setWebsocketEventListener(swigCPtr, this, ConnectionListener.getCPtr(listener), listener);
  }

  public void connect(String url) {
    notificationcenterJNI.SDKManager_connect(swigCPtr, this, url);
  }

  public BusinessManager getBusinessManager() {
    long cPtr = notificationcenterJNI.SDKManager_getBusinessManager(swigCPtr, this);
    return (cPtr == 0) ? null : new BusinessManager(cPtr, true);
  }

  public static long poll() {
    return notificationcenterJNI.SDKManager_poll();
  }

}
