/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dji.notificationcentersdk;

public class AircraftLocation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AircraftLocation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AircraftLocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AircraftLocation obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_AircraftLocation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeight(double value) {
    notificationcenterJNI.AircraftLocation_height_set(swigCPtr, this, value);
  }

  public double getHeight() {
    return notificationcenterJNI.AircraftLocation_height_get(swigCPtr, this);
  }

  public void setElevation(double value) {
    notificationcenterJNI.AircraftLocation_elevation_set(swigCPtr, this, value);
  }

  public double getElevation() {
    return notificationcenterJNI.AircraftLocation_elevation_get(swigCPtr, this);
  }

  public void setLatitude(double value) {
    notificationcenterJNI.AircraftLocation_latitude_set(swigCPtr, this, value);
  }

  public double getLatitude() {
    return notificationcenterJNI.AircraftLocation_latitude_get(swigCPtr, this);
  }

  public void setLongitude(double value) {
    notificationcenterJNI.AircraftLocation_longitude_set(swigCPtr, this, value);
  }

  public double getLongitude() {
    return notificationcenterJNI.AircraftLocation_longitude_get(swigCPtr, this);
  }

  public AircraftLocation() {
    this(notificationcenterJNI.new_AircraftLocation__SWIG_0(), true);
  }

  public AircraftLocation(double height, double elevation, double latitude, double longitude) {
    this(notificationcenterJNI.new_AircraftLocation__SWIG_1(height, elevation, latitude, longitude), true);
  }

}
