/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dji.notificationcentersdk;

public class AircraftLocation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AircraftLocation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AircraftLocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AircraftLocation obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        notificationcenterJNI.delete_AircraftLocation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    notificationcenterJNI.AircraftLocation_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return notificationcenterJNI.AircraftLocation_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    notificationcenterJNI.AircraftLocation_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return notificationcenterJNI.AircraftLocation_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    notificationcenterJNI.AircraftLocation_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return notificationcenterJNI.AircraftLocation_z_get(swigCPtr, this);
  }

  public AircraftLocation() {
    this(notificationcenterJNI.new_AircraftLocation__SWIG_0(), true);
  }

  public AircraftLocation(int x, int y, int z) {
    this(notificationcenterJNI.new_AircraftLocation__SWIG_1(x, y, z), true);
  }

}
