/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dji.notificationcentersdk;

public final class NotificationFrequency {
  public final static NotificationFrequency ANY = new NotificationFrequency("ANY", 0);
  public final static NotificationFrequency ON_CHANGED = new NotificationFrequency("ON_CHANGED", 1);
  public final static NotificationFrequency PUSH_1S = new NotificationFrequency("PUSH_1S", 1000);
  public final static NotificationFrequency PUSH_2S = new NotificationFrequency("PUSH_2S", 2000);
  public final static NotificationFrequency PUSH_3S = new NotificationFrequency("PUSH_3S", 3000);
  public final static NotificationFrequency PUSH_4S = new NotificationFrequency("PUSH_4S", 4000);
  public final static NotificationFrequency PUSH_5S = new NotificationFrequency("PUSH_5S", 5000);
  public final static NotificationFrequency PUSH_10S = new NotificationFrequency("PUSH_10S", 10000);
  public final static NotificationFrequency PUSH_20S = new NotificationFrequency("PUSH_20S", 20000);
  public final static NotificationFrequency PUSH_30S = new NotificationFrequency("PUSH_30S", 30000);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NotificationFrequency swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NotificationFrequency.class + " with value " + swigValue);
  }

  private NotificationFrequency(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NotificationFrequency(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NotificationFrequency(String swigName, NotificationFrequency swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NotificationFrequency[] swigValues = { ANY, ON_CHANGED, PUSH_1S, PUSH_2S, PUSH_3S, PUSH_4S, PUSH_5S, PUSH_10S, PUSH_20S, PUSH_30S };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

