/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dji.notificationcentersdk;

public final class NotificationServerErrorCode {
  public final static NotificationServerErrorCode NotificationServerErrorCode_NoError = new NotificationServerErrorCode("NotificationServerErrorCode_NoError", 0);
  public final static NotificationServerErrorCode NotificationServerErrorCode_ErrorNotSupported = new NotificationServerErrorCode("NotificationServerErrorCode_ErrorNotSupported", -1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NotificationServerErrorCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NotificationServerErrorCode.class + " with value " + swigValue);
  }

  private NotificationServerErrorCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NotificationServerErrorCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NotificationServerErrorCode(String swigName, NotificationServerErrorCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NotificationServerErrorCode[] swigValues = { NotificationServerErrorCode_NoError, NotificationServerErrorCode_ErrorNotSupported };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

